export const categories = [
  { slug: 'indian-dresses', name: 'Indian Dresses', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85' },
  { slug: 'western-dresses', name: 'Western Dresses', image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85' },
  { slug: 'nightwear', name: 'Nightwear', image: 'https://images.unsplash.com/photo-1617331721458-509e4c9d0fcb?auto=format&fit=crop&w=900&q=85' },
  { slug: 'accessories', name: 'Accessories', image: 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=85' },
  { slug: 'footwear', name: 'Footwear', image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85' },
  { slug: 'bags', name: 'Bags', image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85' }
];

export const products = [
  { slug:'rose-anarkali-suit', name:'Rose Embroidered Anarkali Suit', category:'indian-dresses', categoryName:'Indian Dresses', price:89.99, rating:5, reviews:24, image:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85', description:'A graceful embroidered Anarkali designed for festive evenings, celebrations and special occasions.', sizes:['XS','S','M','L','XL'], colour:'Rose Pink' },
  { slug:'emerald-wrap-dress', name:'Emerald Wrap Dress', category:'western-dresses', categoryName:'Western Dresses', price:59.99, rating:4.8, reviews:18, image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85', description:'A flattering wrap silhouette with an easy, elegant feel for dinners, weekends and events.', sizes:['XS','S','M','L'], colour:'Emerald' },
  { slug:'midnight-lace-night-dress', name:'Midnight Lace Night Dress', category:'nightwear', categoryName:'Nightwear', price:34.99, rating:4.9, reviews:15, image:'https://images.unsplash.com/photo-1617331721458-509e4c9d0fcb?auto=format&fit=crop&w=900&q=85', description:'Soft, feminine nightwear with delicate lace detailing and a relaxed fit.', sizes:['S','M','L','XL'], colour:'Black' },
  { slug:'gold-drop-earrings', name:'Gold Drop Earrings', category:'accessories', categoryName:'Accessories', price:19.99, rating:4.9, reviews:10, image:'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=85', description:'Statement drop earrings that add a polished finish to both traditional and modern outfits.', sizes:[], colour:'Gold' },
  { slug:'nude-block-heel-sandals', name:'Nude Block Heel Sandals', category:'footwear', categoryName:'Footwear', price:49.99, rating:4.7, reviews:7, image:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', description:'A versatile block heel with a comfortable silhouette for everyday dressing and occasions.', sizes:['36','37','38','39','40'], colour:'Nude' },
  { slug:'blush-structured-handbag', name:'Blush Structured Handbag', category:'bags', categoryName:'Bags', price:69.99, rating:4.8, reviews:5, image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', description:'A structured everyday handbag with a refined finish and enough room for your essentials.', sizes:[], colour:'Blush' },
  { slug:'ivory-kurta-set', name:'Ivory Printed Kurta Set', category:'indian-dresses', categoryName:'Indian Dresses', price:74.99, rating:4.8, reviews:12, image:'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=900&q=85', description:'An effortless printed kurta set with a soft, contemporary palette.', sizes:['S','M','L','XL'], colour:'Ivory' },
  { slug:'black-satin-slip', name:'Black Satin Slip Dress', category:'western-dresses', categoryName:'Western Dresses', price:64.99, rating:4.9, reviews:21, image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85', description:'A sleek satin slip dress made for evening plans and effortless styling.', sizes:['XS','S','M','L'], colour:'Black' },

  { slug:'blush-printed-kurti', name:'Blush Printed Everyday Kurti', category:'indian-dresses', categoryName:'Indian Dresses', price:39.99, rating:4.6, reviews:16, image:'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=900&q=85', description:'A comfortable printed kurti with an easy silhouette for everyday wear.', sizes:['S','M','L','XL'], colour:'Blush' },
  { slug:'royal-embroidered-lehenga', name:'Royal Embroidered Lehenga Set', category:'indian-dresses', categoryName:'Indian Dresses', price:129.99, rating:4.9, reviews:14, image:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85', description:'A statement embroidered lehenga set designed for weddings, festivities and celebrations.', sizes:['S','M','L','XL'], colour:'Royal Blue' },
  { slug:'white-linen-midi', name:'White Linen Midi Dress', category:'western-dresses', categoryName:'Western Dresses', price:39.99, rating:4.6, reviews:11, image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85', description:'A breezy linen-inspired midi dress with a clean, timeless silhouette.', sizes:['XS','S','M','L'], colour:'White' },
  { slug:'satin-evening-gown', name:'Satin Evening Gown', category:'western-dresses', categoryName:'Western Dresses', price:129.99, rating:4.9, reviews:13, image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85', description:'An elegant floor-length satin gown for dinners, parties and special occasions.', sizes:['XS','S','M','L','XL'], colour:'Burgundy' },
  { slug:'cotton-cloud-pyjama-set', name:'Cotton Cloud Pyjama Set', category:'nightwear', categoryName:'Nightwear', price:39.99, rating:4.8, reviews:19, image:'https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&w=900&q=85', description:'A soft cotton-inspired pyjama set designed for relaxed nights and slow mornings.', sizes:['S','M','L','XL'], colour:'Powder Blue' },
  { slug:'silk-robe-set', name:'Luxe Silk Robe Set', category:'nightwear', categoryName:'Nightwear', price:109.99, rating:4.9, reviews:8, image:'https://images.unsplash.com/photo-1617331721458-509e4c9d0fcb?auto=format&fit=crop&w=900&q=85', description:'A premium robe and nightwear set with a smooth finish and elegant drape.', sizes:['S','M','L','XL'], colour:'Champagne' },
  { slug:'pearl-charm-bracelet', name:'Pearl Charm Bracelet', category:'accessories', categoryName:'Accessories', price:39.99, rating:4.8, reviews:17, image:'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=85', description:'A delicate pearl-inspired bracelet that layers beautifully with everyday jewellery.', sizes:[], colour:'Pearl' },
  { slug:'crystal-statement-necklace', name:'Crystal Statement Necklace', category:'accessories', categoryName:'Accessories', price:79.99, rating:4.9, reviews:12, image:'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=85', description:'A polished statement necklace designed to elevate festive and evening looks.', sizes:[], colour:'Gold' },
  { slug:'heritage-jewellery-set', name:'Heritage Jewellery Set', category:'accessories', categoryName:'Accessories', price:129.99, rating:5, reviews:9, image:'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=85', description:'A premium coordinated jewellery set inspired by timeless Indian occasion styling.', sizes:[], colour:'Antique Gold' },
  { slug:'woven-flat-sandals', name:'Woven Flat Sandals', category:'footwear', categoryName:'Footwear', price:39.99, rating:4.6, reviews:10, image:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', description:'Lightweight woven sandals made for easy summer dressing and everyday comfort.', sizes:['36','37','38','39','40'], colour:'Tan' },
  { slug:'leather-strap-heels', name:'Leather Strap Heels', category:'footwear', categoryName:'Footwear', price:79.99, rating:4.8, reviews:15, image:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', description:'A refined strappy heel that works beautifully for dinners, events and occasions.', sizes:['36','37','38','39','40'], colour:'Black' },
  { slug:'premium-crystal-heels', name:'Premium Crystal Occasion Heels', category:'footwear', categoryName:'Footwear', price:129.99, rating:4.9, reviews:6, image:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', description:'Elegant crystal-detail heels designed to make a statement at special occasions.', sizes:['36','37','38','39','40'], colour:'Silver' },
  { slug:'canvas-mini-crossbody', name:'Canvas Mini Crossbody Bag', category:'bags', categoryName:'Bags', price:39.99, rating:4.6, reviews:13, image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', description:'A compact everyday crossbody with a relaxed canvas-inspired finish.', sizes:[], colour:'Cream' },
  { slug:'quilted-shoulder-bag', name:'Quilted Shoulder Bag', category:'bags', categoryName:'Bags', price:89.99, rating:4.8, reviews:18, image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', description:'A softly structured quilted shoulder bag with room for your daily essentials.', sizes:[], colour:'Black' },
  { slug:'italian-leather-tote', name:'Italian Leather Tote', category:'bags', categoryName:'Bags', price:149.99, rating:4.9, reviews:7, image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', description:'A premium leather-inspired tote with a timeless shape for work and weekends.', sizes:[], colour:'Tan' },
  { slug:'silky-lounge-set', name:'Silky Lounge Set', category:'nightwear', categoryName:'Nightwear', price:44.99, rating:4.7, reviews:9, image:'https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&w=900&q=85', description:'A relaxed two-piece lounge set with a smooth, lightweight feel.', sizes:['S','M','L','XL'], colour:'Champagne' }
];

export function getProduct(slug) { return products.find(p => p.slug === slug); }
export function getCategory(slug) { return categories.find(c => c.slug === slug); }
